### PR TITLE
avoiding panic in passthrough RNG

### PR DESCRIPTION
**Pull request by mimoo**
There is no reason to panic if the seed passed to a `PassThrough` RNG gets depleted. We can just return 0s instead.

### CODE REVIEW

**Comment by AltSysrq** [comment]
I have this staged to the `0.10.0-changes` branch. It's not going in today since the appveyor tests take forever, so probably tomorrow evening US time.

I did simplify the logic here a bit: https://github.com/AltSysrq/proptest/commit/475dd442ae1da5b65659c05c8b4bd77c7e5ca0e1

**Comment by mimoo** [comment]
thanks @AltSysrq !

**Comment by sunshowers** [comment]
I'll try and submit a PR shortly to remove references to `TupleUnion` and replace them with `LazyTupleUnion` for the 0.10 branch. Would be worth getting in for API cleanliness.

**Comment by sunshowers** [comment]
@AltSysrq See #195 for the removal of the old TupleUnion. It's a breaking change so I hope it can make it in time for 0.10! :)

**Pull request merged**
