### PR TITLE
Add `#[proptest]` proc-macro with `#[strategy]` argument attributes

### PR DESCRIPTION
**Pull request by thomaseizinger**
This is based on the work from @davidbarsky in https://github.com/AltSysrq/proptest/pull/166 but expands on it to allow for multiple strategies by making use of argument attributes.

### CODE REVIEW

**Comment by davidbarsky** [comment]
I'd prefer if this branch could be used instead of my PR. I can close my PR, if that'll be helpful?

**Comment by thomaseizinger** [comment]
> I'd prefer if this branch could be used instead of my PR. I can close my PR, if that'll be helpful?

Glad to see you find it helpful :)

I've run into two problems unfortunately:

1. I had to raise MSRV to 1.39 to support argument-position attributes on stable.
2. The nightly build fails because there seems to be a difference between how nightly and stable report spans. You can see it in the appveyor build failing.

**Comment by thomaseizinger** [comment]
> I'd prefer if this branch could be used instead of my PR. I can close my PR, if that'll be helpful?

Glad to see you find it helpful :)

I did have to bump the MSRV to 1.39 to allow for attributes in argument positions to work. I also had to add a dependency on https://github.com/dtolnay/rustversion to disable the UI tests on nightly because the output would be different an `trybuild` would fail because of that. See this issue here: https://github.com/dtolnay/trybuild/issues/36

**Comment by thomaseizinger** [comment]
@AltSysrq This one now passes CI and is ready for review :)

**Comment by thomaseizinger** [comment]
@AltSysrq I re-read the contribution guidelines and updated this PR with what is suggested in there.
I also reverted the original MSRV change and instead extended the CI config to only test the `proptest-attributes` crate with Rust 1.39.

Are you happy to include this crate within this workspace? Otherwise, would you be okay with me publishing / maintaining it myself under the `proptest-attributes` name?

**Comment by thomaseizinger** [comment]
Closing this in favor of https://crates.io/crates/test-strategy.

**Pull request closed without merging**
