### PR TITLE
Travis test unstable

### PR DESCRIPTION
**Pull request by MasonRemaley**
I think I might've figured out how to test with unstable enabled on travis, I couldn't figure out how to test it with travis on my fork so this PR is a work in progress for now until I see if Travis does what I expect, will reply to this again once I get it working.

### CODE REVIEW

**Comment by MasonRemaley** [comment]
Ah turns out that's not really what that environment variable does, I'll mess with this some more later.

**Comment by MasonRemaley** [comment]
Ah nice thanks for the links! I'll try setting it up the way you have it in `proptest-arbitrary`.

**Comment by MasonRemaley** [comment]
Awesome, this seems to be working  now!

Btw is there a reason to do `cargo build; cargo test` instead of just `cargo test`? I set this up to do the former since that's what you have in `proptest-arbitrary` but I'm not sure what the difference is.

**Comment by MasonRemaley** [comment]
Neat, it actually turns out that `travis-cargo` automatically sets a  feature named unstable when appropriate. Works now!

**Comment by Centril** [comment]
Perhaps we should not allow failures on nightly and require that a commit be made fixing those changes?
It would be nice if failures were more noticeable.

**Comment by AltSysrq** [comment]
@MasonRemaley Thanks for the contribution!

@Centril Agreed, I'll make that change after merging.

**Comment by MasonRemaley** [comment]
No problem!

**Pull request merged**
